var Activity=new Class({Implements:[Events,Options],eventListener:{},initialize:function(a,b){this.setOptions(b);this.eventBus=a;element=b.element?$(b.element):window;this.view=this.view?new this.view(element,this.options.view):element;var c=this.eventListener;for(var d in c){var g=c[d];for(var e in g)this[d].addEvent(e,this[g[e]].bind(this))}this.build()},build:$empty,toElement:function(){return this.view},destroy:function(){this.view!=window&&this.view.destroy()}}),Model=new Class({Implements:[Events,
Options],options:{useLocalStorage:true},initialize:function(a,b){this.setOptions(b);this.eventBus=a;if(this.hasLocalStorage=this.hasLocalStorage()){Storage.prototype.setObject=function(c,d){this.setItem(c,JSON.stringify(d))};Storage.prototype.getObject=function(c){return JSON.parse(this.getItem(c))}}this.cache={}},hasLocalStorage:function(){try{return this.options.useLocalStorage&&"localStorage"in window&&window.localStorage!==null}catch(a){return false}},get:function(a,b,c){return c&&this.hasLocalStorage?
localStorage[b?"getObject":"getItem"](a)||undefined:this.cache[a]||undefined},set:function(a,b,c){if(c&&this.hasLocalStorage)if(typeof b!=="string")localStorage.setObject(a,b);else try{localStorage.setItem(a,b)}catch(d){if(d.name=="QUOTA_EXCEEDED_ERR")throw new Exception(b);}else this.cache[a]=b;this.eventBus.fireEvent("changed",a);return b},clear:function(a,b){b&&this.hasLocalStorage&&localStorage.removeItem(a);delete this.cache[a];this.eventBus.fireEvent("changed",a)}}),EventBus=new Class({Implements:Events}),
View=new Class({Implements:[Events,Options],initialize:function(a,b){var c=$type(a);if(c!="element"&&c!="window")throw"Type of element should be element or window but is "+c;this.setOptions(b);this.element=a;this.build();return this},build:$empty,toElement:function(){return this.element},set:function(a,b){this.chooseGetterSetter("set",a,b);return this},get:function(a){return this.chooseGetterSetter("get",a)},chooseGetterSetter:function(a,b,c){var d=a+b.capitalize();return this[d]?this[d](c):this.element[a](b,
c)}});Element.implement({setRole:function(a){return this.setProperty("role",a)},ariaChecked:function(a){return this.setProperty("aria-checked",a)}});Elements.implement({setRole:function(a){return this.setProperty("role",a)},ariaChecked:function(a){return this.setProperty("aria-checked",a)}});
var Aria=new Class({Implements:[Events,Options],buildAria:$empty,ownedElements:{},setAria:function(a){this.setOptions(a);this.initializeElement();this.buildAria()},initializeElement:function(){for(var a=this.settings.roles,b=a.length,c=this.options.selectors,d=this.options.ariaAttributes||{},g=this.settings.ariaAttributes||{},e=0;e<b;e++){var f=a[e],h=$merge(d[f],g[f]),i=(e?this.element.getElements(c[f]):$(c[f])).setRole(f).setProperty("tabindex",e?-1:0);if(h)for(var j in h)i.setProperty("aria-"+
j,h[j]);this[f]=i;if(!e)this.element=i}}});
Aria.Listbox=new Class({Extends:Aria,options:{selectors:{option:"li"},activeElement:null,ariaAttributes:{}},settings:{roles:["listbox","option"]},buildAria:function(){var a=this.settings.roles.getLast();this.element.addEvent("click:relay("+this.options.selectors[a]+")",this.check.bind(this)).addEvent("keyup",this.keys.bindWithEvent(this));this[a].ariaChecked(false);this.checkedElements=this.settings.activeElement?$$(this.settings.activeElement).ariaChecked(true):new Elements;this.multiselectable=
this.options.ariaAttributes.listbox},check:function(a,b,c){if(this.checkedElements.length==1)this.lastDirection=c;var d=this.multiselectable;if(b){if(d&&a.shift)this.lastDirection&&c!=this.lastDirection?this.checkedElements.pop().ariaChecked(false):this.checkedElements.push(b.ariaChecked(true));else{this.checkedElements.ariaChecked(false);this.checkedElements=$$(b.ariaChecked(true))}this.checkedElements.getLast().focus();this.fireEvent("changed",d?this.checkedElements:this.checkedElements[0])}},keys:function(a){var b=
a.key;b=b.test(/left|up/)?"Previous":b.test(/right|down/)?"Next":"";a.stop&&a.stop();if(b){var c=this.checkedElements.length?this.checkedElements.getLast()["get"+b]():$(this[this.settings.roles.getLast()][0]);this.check(a,c,b)}}});
Aria.Radiogroup=new Class({Extends:Aria.Listbox,options:{selectors:{radio:"li"},activeElement:null},settings:{roles:["radiogroup","radio"],ariaAttributes:{radiogroup:{multiselectable:false}}},buildAria:function(){this.parent();this.checkedElements=$$(this.settings.activeElement||this.radio[0]).ariaChecked(true)}});
Aria.Combobox=new Class({Extends:Aria.Listbox,options:{selectors:{listbox:"ul",option:"li",textbox:"span"},activeElement:null},settings:{roles:["combobox","listbox","textbox","option"],ariaAttributes:{combobox:{expanded:false}}},buildAria:function(){this.parent();this.element.addEvents({focus:this.openList.bind(this)});this.textbox[0].addEvent("click",this.toggleList.bind(this))},check:function(a,b,c){this.parent(a,b,c);this.closeList(a)},openList:function(){if(!this.open){this.element.setProperty("aria-expanded",
true);this.fireEvent("opened");this.open=true}},toggleList:function(){this[(this.open?"close":"open")+"List"]()},closeList:function(){this.element.setProperty("aria-expanded",false);this.fireEvent("closed");this.open=false}});
